#!/bin/bash

# Check out the latest release available on <https://go.dev/doc/install>
VERSION="1.21.0"
OUT_DIR="/home/julien/Downloads"

# GOLANG_LATEST_STABLE_VERSION=$(curl https://go.dev/dl/\?mode=json | grep -o 'go.*.linux-amd64.tar.gz' | head -n 1 | tr -d '\r\n' )

# Download the release from Google
curl -o ${OUT_DIR}/go${VERSION}.linux-amd64.tar.gz -L "https://dl.google.com/go/go${VERSION}.linux-amd64.tar.gz"

# Remove any previous Go installation
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "${OUT_DIR}/go${VERSION}.linux-amd64.tar.gz"

# Show version
go version
